### ISSUE TITLE
Show examples of more JQL and example graphs with more interesting data

### ISSUE THREAD

**Issue by buep** [Praqma/atlassian-metrics#2]
Maybe a section more in the readme, where we explain how to experiment with it. Make yourself a JQL, expose it as a REST and get the data in Prometheus.

**Comment by buep** [comment]
scrape_configs:
  - job_name: 'jira'
    scheme: http
    metrics_path: '/plugins/servlet/prometheus/metrics'
    # params:
    #     token: ['00000000000000000000000000000000000']
    static_configs:
      - targets: ['172.17.0.2:8080']
  - job_name: 'jirascriptrunner'
    scheme: http
    basic_auth:
      username: admin
      password: mypass
    metrics_path: '/rest/scriptrunner/latest/custom/getInactiveIssues'
    static_configs:
      - targets: ['172.17.0.2:8080']

**Comment by buep** [comment]
But this curl command works

curl -u admin:mypass http://jira.teamsinspace.com:8080/rest/scriptrunner/latest/custom/getInactiveIssues

**Comment by buep** [comment]
Prometheus reports: 

```
level=warn ts=2018-06-05T15:51:38.102356474Z caller=scrape.go:697 component="scrape manager" scrape_pool=jirascriptrunner target=http://172.17.0.2:8080/rest/scriptrunner/latest/custom/getInactiveIssues msg="append failed" err="no token found"
```

**Comment by buep** [comment]
Oh, I think the problem is not auth.. but probably that the script doesn't return prometheus language...

@sheeeng did you notice that? Did you try to make the scriptrunner send out prometheus data?

**Comment by sheeeng** [comment]
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
